### PR TITLE
Metadata Builder

### PR DESCRIPTION
**Pull request by allmightyspiff**
This feature changes how sldn is built. Almost all data is going to be in `data/sldn_metadata.json`. So that in the future, really only this file needs to be updated instead of every file in this project.

### CODE REVIEW

**Comment by allmightyspiff** [comment]
For testing on this issue, I mostly need help with spot-checking against sldn.softlayer.com to note any differences. This change only really effects the reference section (https://sldn.softlayer.com/reference/softlayerapi/) . You should be able to run `./hugo server  -b http://localhost -d html/`  locally in this project to see the changes.

Things I know are different:
- Space on the method list isn't the same
- Links for Required/Optional headers are different. They now link to an article explaining how those work instead of nothing.
- Types/Services might be missing `AssociatedMethods` which is fine for now.

**Comment by BrianSantivanez** [comment]
Suggested changes to add (the images contains the URL to can refer service, example and language)
image
image
image
image

**Comment by BrianSantivanez** [comment]
Changes found in get methods(SoftLayer_Account::getAbuseEmail, SoftLayer_Account::getUsers, SoftLayer_Hardware::getComponents, SoftLayer_Hardware::getHardwareStatus, etc)
image

**Comment by edsonarios** [comment]
Hi, I found the following differences, between local and sldn.softlayer

1. Extra space is found in any datatypes file
image
image

2. An extra data of None appeared, before nothing appeared
image
image

In all pages, the links in the Overview and parameter section do not work, but the Return Values work normally, I'm not sure if that meant: "Types / Services might be missing AssociatedMethods which is fine for now."
image

**Comment by BrianSantivanez** [comment]
The Error Handling items are displayed in different format (example SoftLayer_Account::editAccount)
image

**Comment by BrianSantivanez** [comment]
The attribute "attachmentType" is not displayed is list format (SoftLayer_Ticket::createStandardTicket)
image

**Comment by edsonarios** [comment]
Observations:
There are several changes that are not seen in sldn.softlayer.com but I am not sure if it is because they will only come out in the next release.
For Example:
image
image

Elements decrecated in several places
image
image
In this same image, change the "integer" to only "int"

**Comment by BrianSantivanez** [comment]
The displayed links of http://localhost:1313/reference/services/SoftLayer_Dns_Domain/ were removed
image

**Comment by BrianSantivanez** [comment]
In /reference/services/SoftLayer_Network_Subnet/ the method route is displaying information that already is displayed in SoftLayer_Network_Subnet::route
image

**Comment by allmightyspiff** [comment]
> Changes found in get methods(SoftLayer_Account::getAbuseEmail, SoftLayer_Account::getUsers, SoftLayer_Hardware::getComponents, SoftLayer_Hardware::getHardwareStatus, etc) 

1. The texted deleted here is intentional. There are 2 parts that this bit comes from, and this specific method (and others like it ) only have the "overview" section, so its intentional I left it blank there.
2. The missing table is also intentional. The empty table looked somewhat bad before in my opinion, so if there are no Parameters, I just put in None.
3. Good catch on the missing "Retrieve" word. I had to look into this a bit more  because that word doesn't actually appear in the source, it looks like it gets added somewhere in the old build process. After looking into it a bit, I think I'm ok with it being left out.

**Comment by allmightyspiff** [comment]
@BrianSantivanez @edsonarios Thanks for the comments, they were very helpful. When you can test out my new changes to make sure I didn't make anything worse. If the changes look good, please also press the "Approve" button on the code review in github (or Requires changes if appropriate ).

**Comment by allmightyspiff** [comment]
> Suggested changes to add (the images contains the URL to can refer service, example and language)

I made https://github.com/softlayer/githubio_source/issues/529 and https://github.com/softlayer/githubio_source/issues/528 to address these issues, as they were present already.

**Comment by edsonarios** [comment]
I have some observations:
1. This link change from services to datatype

Before it referred to the same page, which did not make any change, but the text refers to a service link

image

2. The function to redirect a "Not Found" message is not working
In the case of documentation, it shows the same page but without any text
image
image

Before
image

In the case that refers to a tag that does not exist, it shows the page blank
image
image

Before
image

**Review by BrianSantivanez — DISMISSED** [review]
Looks good to me

**Comment by BrianSantivanez** [comment]
You can confirm that "postInstallScriptUri" attritute of http://localhost:1313/reference/datatypes/SoftLayer_Virtual_Guest/ is deprecated
image

"Deprecated" word of createArchiveTransaction service of http://localhost:1313/reference/services/SoftLayer_Virtual_Guest/ is not displayed
image

**Comment by allmightyspiff** [comment]
@BrianSantivanez Those differences are expected.

**Review by BrianSantivanez — APPROVED** [review]
Looks good to me

**Comment by edsonarios** [comment]
Looks good to me
just with an observation
The Not Found page is not working
Although these pages hardly exist, very few or if we force it
image
image
image

**Review by edsonarios — APPROVED** [review]

**Comment by allmightyspiff** [comment]
@edsonarios The 404 pages dont work the same when running it Hugo locally, but they should work fine when published to github, so no worries there.

The `getToken` method you highlighted is not technically marked as deprecated which is why its not highlighted. It only has the word `(DEPRECATED)` in the description. I might eventually include those in the deprecated highlighting, but for now that behavior is expected.

**Pull request merged**
